name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # Checkout private submodules(themes or something else).

      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'

      # Deploy hexo blog website.
      - name: Setup Hexo
        env:
          # 定义了一个变量 secrets里面添加的名字
          ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          npm install hexo-cli -g
          npm install

      - name: Build
        run: |
          hexo clean
          hexo deploy

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: public
